version: '3.8'
services:
  injozi-frontend:
    image: client-dev-i
    build:
      dockerfile: Dockerfile.dev
    container_name: client-dev-c
    volumes:
      - ./injozi-frontend:/injozi-frontend
      - node_modules:/injozi-frontend/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
volumes:
  node_modules: